[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[dependencies]
tray-icon = "0.24"
sync-core = { path = "../sync-core" }
image = "0.25"
ctrlc = "3.4"
tokio = { version = "1.52", features = ["full"] }
tokio-util = "0.7"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_System_Console"] }
